export type Airport = { iata:string; icao:string; name:string; country:string }
export const CARIB_AIRPORTS: Airport[] = [
  { iata:'AUA', icao:'TNCA', name:'Queen Beatrix', country:'Aruba' },
  { iata:'AXA', icao:'TQPF', name:'Clayton J. Lloyd', country:'Anguilla' },
  { iata:'BGI', icao:'TBPB', name:'Grantley Adams Intl', country:'Barbados' },
  { iata:'BQN', icao:'TJBQ', name:'Rafael Hernández', country:'Puerto Rico' },
  { iata:'BZE', icao:'MZBZ', name:'Philip S. W. Goldson', country:'Belize' },
  { iata:'CUR', icao:'TNCC', name:'Hato Intl', country:'Curaçao' },
  { iata:'DOM', icao:'TDPD', name:'Douglas–Charles', country:'Dominica' },
  { iata:'EIS', icao:'TUPJ', name:'Terrance B. Lettsome', country:'British Virgin Islands' },
  { iata:'GCM', icao:'MWCR', name:'Owen Roberts', country:'Cayman Islands' },
  { iata:'GND', icao:'TGPY', name:'Maurice Bishop Intl', country:'Grenada' },
  { iata:'GEO', icao:'SYCJ', name:'Cheddi Jagan Intl', country:'Guyana' },
  { iata:'HOG', icao:'MUHG', name:'Frank País', country:'Cuba' },
  { iata:'JBQ', icao:'MDJB', name:'La Isabela', country:'Dominican Republic' },
  { iata:'KIN', icao:'MKJP', name:'Norman Manley Intl', country:'Jamaica' },
  { iata:'MBJ', icao:'MKJS', name:'Sangster Intl', country:'Jamaica' },
  { iata:'MNI', icao:'TRPG', name:'John A. Osborne', country:'Montserrat' },
  { iata:'MSY', icao:'KMSY', name:'(edge hub) New Orleans', country:'USA' },
  { iata:'NAS', icao:'MYNN', name:'Lynden Pindling', country:'Bahamas' },
  { iata:'OCJ', icao:'MKBS', name:'Ian Fleming Intl', country:'Jamaica' },
  { iata:'PAP', icao:'MTPP', name:'Toussaint Louverture', country:'Haiti' },
  { iata:'PLS', icao:'MBPV', name:'Providenciales', country:'Turks & Caicos' },
  { iata:'POP', icao:'MDPP', name:'Gregorio Luperón', country:'Dominican Republic' },
  { iata:'POS', icao:'TTPP', name:'Piarco Intl', country:'Trinidad & Tobago' },
  { iata:'PTP', icao:'TFFR', name:'Pointe‑à‑Pitre', country:'Guadeloupe' },
  { iata:'PUJ', icao:'MDPC', name:'Punta Cana', country:'Dominican Republic' },
  { iata:'SAB', icao:'TNCS', name:'Juancho E. Yrausquin', country:'Saba' },
  { iata:'SBH', icao:'TFFJ', name:'Gustaf III', country:'St Barthélemy' },
  { iata:'SDQ', icao:'MDSD', name:'Las Américas', country:'Dominican Republic' },
  { iata:'SJU', icao:'TJSJ', name:'Luis Muñoz Marín', country:'Puerto Rico' },
  { iata:'SKB', icao:'TKPK', name:'Robert L. Bradshaw Intl', country:'St. Kitts & Nevis' },
  { iata:'SLU', icao:'TLPC', name:'George F. L. Charles', country:'St. Lucia' },
  { iata:'STT', icao:'TIST', name:'Cyril E. King', country:'USVI' },
  { iata:'STX', icao:'TISX', name:'Henry E. Rohlsen', country:'USVI' },
  { iata:'SXM', icao:'TNCM', name:'Princess Juliana', country:'Sint Maarten' },
  { iata:'TAB', icao:'TTCP', name:'A.N.R. Robinson Intl', country:'Tobago' },
  { iata:'UVF', icao:'TLPL', name:'Hewanorra Intl', country:'St. Lucia' },
  { iata:'VQS', icao:'TJVQ', name:'Antonio Rivera Rodríguez', country:'Vieques PR' },
  { iata:'VRA', icao:'MUVR', name:'Juan Gualberto Gómez', country:'Cuba' },
  { iata:'SDQ', icao:'MDSD', name:'Las Américas Intl', country:'Dominican Republic' },
  { iata:'BON', icao:'TNCB', name:'Flamingo', country:'Bonaire' }
];
