export type Airport = { iata: string; icao: string; name: string; country: string };
export const CARIBBEAN_AIRPORTS: Airport[] = [
  { iata: 'ANU', icao: 'TAPA', name: 'V. C. Bird Intl', country: 'Antigua & Barbuda' },
  { iata: 'AUA', icao: 'TNCA', name: 'Queen Beatrix Intl', country: 'Aruba' },
  { iata: 'NAS', icao: 'MYNN', name: 'Lynden Pindling Intl', country: 'Bahamas' },
  { iata: 'BGI', icao: 'TBPB', name: 'Grantley Adams Intl', country: 'Barbados' },
  { iata: 'BZE', icao: 'MZBZ', name: 'Philip S. W. Goldson Intl', country: 'Belize' },
  { iata: 'GCM', icao: 'MWCR', name: 'Owen Roberts Intl', country: 'Cayman Islands' },
  { iata: 'HAV', icao: 'MUHA', name: 'José Martí Intl', country: 'Cuba' },
  { iata: 'DOM', icao: 'TDPD', name: 'Douglas–Charles', country: 'Dominica' },
  { iata: 'SDQ', icao: 'MDSD', name: 'Las Américas', country: 'Dominican Republic' },
  { iata: 'GND', icao: 'TGPY', name: 'Maurice Bishop Intl', country: 'Grenada' },
  { iata: 'PTP', icao: 'TFFR', name: 'Pôle Caraïbes', country: 'Guadeloupe' },
  { iata: 'PAP', icao: 'MTPP', name: 'Toussaint Louverture', country: 'Haiti' },
  { iata: 'KIN', icao: 'MKJP', name: 'Norman Manley Intl', country: 'Jamaica' },
  { iata: 'MBJ', icao: 'MKJS', name: 'Sangster Intl', country: 'Jamaica' },
  { iata: 'FDF', icao: 'TFFF', name: 'Martinique Aimé Césaire', country: 'Martinique' },
  { iata: 'MNI', icao: 'TRPG', name: 'John A. Osborne', country: 'Montserrat' },
  { iata: 'SJU', icao: 'TJSJ', name: 'Luis Muñoz Marín Intl', country: 'Puerto Rico' },
  { iata: 'SKB', icao: 'TKPK', name: 'Robert L. Bradshaw Intl', country: 'St. Kitts & Nevis' },
  { iata: 'UVF', icao: 'TLPL', name: 'Hewanorra Intl', country: 'St. Lucia' },
  { iata: 'SXM', icao: 'TNCM', name: 'Princess Juliana Intl', country: 'Sint Maarten' },
  { iata: 'SFG', icao: 'TFFG', name: 'Grand Case', country: 'Saint Martin (FR)' },
  { iata: 'SVD', icao: 'TVSA', name: 'Argyle Intl', country: 'St. Vincent & the Grenadines' },
  { iata: 'GEO', icao: 'SYCJ', name: 'Cheddi Jagan Intl', country: 'Guyana' },
  { iata: 'POS', icao: 'TTPP', name: 'Piarco Intl', country: 'Trinidad & Tobago' },
  { iata: 'TAB', icao: 'TTCP', name: 'A. N. R. Robinson Intl', country: 'Trinidad & Tobago' },
  { iata: 'PLS', icao: 'MBPV', name: 'Providenciales Intl', country: 'Turks & Caicos' },
  { iata: 'STT', icao: 'TIST', name: 'Cyril E. King', country: 'US Virgin Islands' },
  { iata: 'STX', icao: 'TISX', name: 'Henry E. Rohlsen', country: 'US Virgin Islands' }
];
