export const SLUG_TO_COUNTRY: Record<string, string> = {
  "antigua-and-barbuda":"Antigua & Barbuda",
  "aruba":"Aruba",
  "bahamas":"Bahamas",
  "barbados":"Barbados",
  "belize":"Belize",
  "bermuda":"Bermuda",
  "british-virgin-islands":"British Virgin Islands",
  "cayman-islands":"Cayman Islands",
  "dominica":"Dominica",
  "dominican-republic":"Dominican Republic",
  "grenada":"Grenada",
  "guyana":"Guyana",
  "haiti":"Haiti",
  "jamaica":"Jamaica",
  "montserrat":"Montserrat",
  "st-kitts-and-nevis":"St. Kitts and Nevis",
  "saint-lucia":"Saint Lucia",
  "st-vincent-and-the-grenadines":"Saint Vincent and the Grenadines",
  "trinidad-and-tobago":"Trinidad and Tobago",
  "sint-maarten":"Sint Maarten",
  "puerto-rico":"Puerto Rico",
  "us-virgin-islands":"United States Virgin Islands"
};